use_frameworks!


target 'AwesomeBubbles_Example' do
  pod 'AwesomeBubbles', :path => '../'

  target 'AwesomeBubbles_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'FBSnapshotTestCase'
  end
end
